name: build-and-push

on:
    release:
        types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup shc tool
      run: |
        sudo apt-get update && sudo apt-get install software-properties-common -y
        sudo add-apt-repository ppa:neurobin/ppa -y
        sudo apt-get update && sudo apt-get install shc -y
    - name: Create new binary using script
      run: |
        rm -f akslabs_binaries/*
        bash shc_script_converter.sh
    - name: Login to Docker Registry
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
    - name: Get the version
      run: echo ::set-env name=TAG_ID::$(echo ${GITHUB_REF:10})
    - name: Build the tagged Docker image
      run: docker build . --file Dockerfile -t sturrent/akslabs:"${{ env.TAG_ID }}"
    - name: Push the tagged Docker image
      run: docker push sturrent/akslabs:"${{ env.TAG_ID }}"
    - name: Tag the latest Docker image
      run: docker tag sturrent/akslabs:"${{ env.TAG_ID }}" sturrent/akslabs:latest
    - name: Push the latest Docker image
      run: docker push sturrent/akslabs:latest
